# EE3305/ME3243
# Name: Sim Justin
# NUSNET ID: E0968898

dt: 0.1

target_distance: 1.1
target_angle: 0

# Ku 50 Tu 2
Kp_f: 15
Ki_f: 15
Kd_f: 8

# Ku 10 Tu 3.2
Kp_a: 4.25
Ki_a: 3
Kd_a: 2

pillar_x: 7.5
pillar_y: 4